// task10-angular/one-piece/src/app/components/characters/characters.component.ts
import { Component, OnInit } from '@angular/core';
import {getElementPage} from "../../api/createObj";
import OnePiceInformation from "../../../json/OnePiceInformation.json";

@Component({
  selector: 'app-characters',
  templateUrl: './characters.component.html',
  styleUrls: ['./characters.component.scss']
})
export class CharactersComponent implements OnInit {

  constructor() { }

  characters: any;

  ngOnInit(): void {

    const config = {
      classDesktop: 'col-6 col-sm-3 col-md-3 col-xl-3 col-lg-3 position-relative',
      classMobile: 'col-6 col-sm-3 col-md-3 col-xl-3 col-lg-3 position-relative d-none d-sm-block d-md-block',
      countElementsWeb: 4,
      countElementsMovil: 2
    };

    this.characters = getElementPage(OnePiceInformation.characters, config);
  }

}

<div id="islands">
    <div class="row">
        <div class="col-6 text-start"><h4>Character</h4></div>
        <div class="col-6 text-end"><a [routerLink]="['/charactersPage']">See all</a></div>
    </div>

    <div class="row" id="list">
        <div id="divMain" [ngClass]="i.class" *ngFor="let i of characters">
            <div class="characterText textGeneral d-flex flex-column justify-content-center">
                <div id="name">{{i.name}}</div>
            </div>
            <div class="pickgradient">
                <img id="img" alt="Rectangle10" class="img-fluid" [srcset]="'assets/img/character/' + i.img" src=""/>
            </div>
        </div>
    </div>
</div>

// task09-reactjs/one-piece/src/components/Characters/Characters.tsx
import './Characters.scss'

import Character from "./Character/Character";
import OnePiceInformation from '../../json/OnePiceInformation.json'
import {getElementPage} from '../createObj'

function Characters() {

    const config = {
        classDesktop: 'col-6 col-sm-3 col-md-3 col-xl-3 col-lg-3 position-relative',
        classMobile: 'col-6 col-sm-3 col-md-3 col-xl-3 col-lg-3 position-relative d-none d-sm-block d-md-block',
        countElementsWeb: 4,
        countElementsMovil: 2
    };

    let characters = getElementPage(OnePiceInformation.characters, config);

    return (
        <div id="character">
            <div className="row">
                <div className="col-6 text-start"><h4>Character</h4></div>
                <div className="col-6 text-end"><a href="characters.html">See all</a></div>
            </div>
            <div className="row" id="list">
                {
                    characters.map((item) => {
                        return <Character
                            key={item.name}
                            name={item.name}
                            img={item.img.toString()}
                            class={item.class}/>
                    })
                }
            </div>
        </div>
    )
}

export default Characters;
