// task10-angular/one-piece/src/app/components/mist-object/mist-object.component.ts
import { Component, OnInit } from '@angular/core';
import {getElementPage} from "../../api/createObj";
import OnePiceInformation from 'src/json/OnePiceInformation.json'

@Component({
  selector: 'app-mist-object',
  templateUrl: './mist-object.component.html',
  styleUrls: ['./mist-object.component.scss']
})
export class MistObjectComponent implements OnInit {

  constructor() { }

  mysticObjects: any;

  ngOnInit(): void {
    const config = {
      classDesktop: 'col-12 col-sm-6 col-md-6 col-xl-6 col-lg-6 position-relative',
      classMobile: 'col-12 col-md-6 col-xl-6 col-sm-6 col-lg-6 position-relative d-none d-sm-block d-md-block',
      countElementsWeb: 4,
      countElementsMovil: 3
    };

    this.mysticObjects = getElementPage(OnePiceInformation.mysticObjects, config);
  }

}

<div id="MistObjects">
    <div class="row">
        <div class="col-6 text-start"><h4>Mist Object</h4></div>
        <div class="col-6 text-end"><a [routerLink]="['/mistObjectPage']">See all</a></div>
    </div>

    <div class="row contentMistObjets" id="list">

        <div id="divMain" [ngClass]="i.class" *ngFor="let i of mysticObjects">
            <div class="mt-2"></div>
            <div class="mistObjText">
                <div class="textDivImg mt-2" id="name">{{i.name}}</div>
                <div class="mt-2"></div>
                <div class="textDivImg" id="desc">{{i.description}}</div>
            </div>
            <img alt="Rectangle4" id="img" class="img-fluid" [srcset]="'assets/img/mistObjects/' + i.img" src=""/>
        </div>

    </div>
</div>

// task09-reactjs/one-piece/src/components/MistObject/MistObject.tsx
import './MistObject.scss'

import Object from "./Object/Object";
import {getElementPage} from "../createObj";
import OnePiceInformation from "../../json/OnePiceInformation.json";


function MistObject() {

    const config = {
        classDesktop: 'col-12 col-sm-6 col-md-6 col-xl-6 col-lg-6 position-relative',
        classMobile: 'col-12 col-md-6 col-xl-6 col-sm-6 col-lg-6 position-relative d-none d-sm-block d-md-block',
        countElementsWeb: 4,
        countElementsMovil: 3
    };

    let mysticObjects = getElementPage(OnePiceInformation.mysticObjects, config);

    return (
        <div id="MistObjects">
            <div className="row">
                <div className="col-6 text-start"><h4>Mist Object</h4></div>
                <div className="col-6 text-end"><a href="mist-objects.html">See all</a></div>
            </div>

            <div className="row contentMistObjets" id="list">
                {
                    mysticObjects.map((item) => {
                        return <Object
                            key={item.name}
                            name={item.name}
                            description={item.description}
                            img={item.img.toString()}
                            class={item.class}/>
                    })
                }
            </div>
        </div>
    )
}

export default MistObject;
