// task10-angular/one-piece/src/app/components/islands/islands.component.ts
import {Component, OnInit} from '@angular/core';
import {getElementPage} from 'src/app/api/createObj'
import OnePiceInformation from 'src/json/OnePiceInformation.json'

// import img from 'src/assets/img/islands'

@Component({
    selector: 'app-islands',
    templateUrl: './islands.component.html',
    styleUrls: ['./islands.component.scss']
})
export class IslandsComponent implements OnInit {

    constructor() {
    }

    islands: any;

    ngOnInit(): void {
        const config = {
            classDesktop: 'col-6 col-md-4 col-sm-4 col-xl-4 col-lg-4 position-relative',
            classMobile: 'col-6 col-md-4 col-sm-4 col-xl-4 col-lg-4 position-relative d-none d-sm-block d-md-block',
            countElementsWeb: 3,
            countElementsMovil: 2
        };

        this.islands = getElementPage(OnePiceInformation.islands, config);
    }

}

<div id="islands">
    <div class="row">
        <div class="col-6 text-start"><h4>Islands</h4></div>
        <div class="col-6 text-end"><a [routerLink]="['/islandsPage']">See all</a></div>
    </div>

    <div class="row" id="list">
        <div id="divMain" [ngClass]="i.class" *ngFor="let i of islands">
            <div class="islandsText d-flex flex-column justify-content-center textGeneral">
                <div class="textDivImg"><span class="islandsTextHeader" id="name">{{i.name}}</span></div>
                <div class="textDivImg">
                    <img alt="Rectangle4" class="img-fluid" srcSet="assets/img/icon/geo.png" src=""/>
                    <span id="Location">{{i.Location}}</span>
                </div>
            </div>
            <img id="img" alt="Rectangle8" class="img-fluid" [srcset]="'assets/img/islands/' + i.img" src=""/>
        </div>

    </div>
</div>

// task09-reactjs/one-piece/src/components/Islands/Islands.tsx
import './Islands.scss'

import Island from "./Island/Island";
import OnePiceInformation from '../../json/OnePiceInformation.json'
import {getElementPage} from '../createObj'

function Islands() {

    const config = {
        classDesktop: 'col-6 col-md-4 col-sm-4 col-xl-4 col-lg-4 position-relative',
        classMobile: 'col-6 col-md-4 col-sm-4 col-xl-4 col-lg-4 position-relative d-none d-sm-block d-md-block',
        countElementsWeb: 3,
        countElementsMovil: 2
    };


    let islands = getElementPage(OnePiceInformation.islands, config);


    return (

        <div id="islands">
            <div className="row">
                <div className="col-6 text-start"><h4>Islands</h4></div>
                <div className="col-6 text-end"><a href="islands.html">See all</a></div>
            </div>

            <div className="row" id="list">
                {
                    islands.map((item) => {
                        return <Island
                            key={item.name}
                            name={item.name}
                            Location={item.Location}
                            img={item.img.toString()}
                            class={item.class}/>
                    })
                }
            </div>
        </div>

    )
}

export default Islands;
